DECISION_TREE_BASE_SCORE = 0.80920
XGBOOST_BASE_SCORE = 0.81148
RANDOM_FOREST_BASE_SCORE = 0.80924
LIGHTGBM_BASE_SCORE = 0.82382
CATBOOST_BASE_SCORE = 0.81709

BASELINE_SCORE = {
    "dt": DECISION_TREE_BASE_SCORE,
    "xgb": XGBOOST_BASE_SCORE,
    "rf": RANDOM_FOREST_BASE_SCORE,
    "lgbm": LIGHTGBM_BASE_SCORE,
    "cb": CATBOOST_BASE_SCORE,
}

DECISION_TREE_KAGGLE_SCORE = 0.77511
XGBOOST_KAGGLE_SCORE = 0.75119
RANDOM_FOREST_KAGGLE_SCORE = 0.76555
LIGHTGBM_KAGGLE_SCORE = 0.76794
CATBOOST_KAGGLE_SCORE = 0.78229

KAGGLE_BASELINE_SCORE = {
    "dt": DECISION_TREE_KAGGLE_SCORE,
    "xgb": XGBOOST_KAGGLE_SCORE,
    "rf": RANDOM_FOREST_KAGGLE_SCORE,
    "lgbm": LIGHTGBM_KAGGLE_SCORE,
    "cb": CATBOOST_KAGGLE_SCORE,
}
