DECISION_TREE_BASE_SCORE = 0.80920
XGBOOST_BASE_SCORE = 0.81148
RANDOM_FOREST_BASE_SCORE = 0.80924
LIGHTGBM_BASE_SCORE = 0.82382
CATBOOST_BASE_SCORE = 0.81709

BASELINE_SCORE = {
    "dt": DECISION_TREE_BASE_SCORE,
    "xgb": XGBOOST_BASE_SCORE,
    "rf": RANDOM_FOREST_BASE_SCORE,
    "lgbm": LIGHTGBM_BASE_SCORE,
    "cb": CATBOOST_BASE_SCORE,
}
